<?php

## WARNING: THIS FILE IS GENERATED BY PLANSYS
## DO NOT CHANGE.
$mode = "init";

## Define Root Dir
$root = $mode != "init" ? dirname(__FILE__) . '/plansys' : dirname(__FILE__);

## Define core lib path
$yii      = $root . '/framework/yii.php';
$config   = $root . '/config/main.php';
$setting  = $root . '/components/utility/Setting.php';
$composer = require ($root . '/vendor/autoload.php');

## Initialize settings
require_once ($setting);
Setting::init($config, $mode, __FILE__);

## Initialize Yii
require_once ($yii);
Yii::createWebApplication($config)->run();