// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "git.apache.org/thrift.git/lib/go/thrift"
        "state"
)


func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  void disconnect(Client client, string reason)")
  fmt.Fprintln(os.Stderr, "  void send(Client client, string message)")
  fmt.Fprintln(os.Stderr, "   getClients(Client client)")
  fmt.Fprintln(os.Stderr, "  void setTag(Client client, string tag)")
  fmt.Fprintln(os.Stderr, "  i32 stateCount(string db)")
  fmt.Fprintln(os.Stderr, "  void stateSet(string db, string key, string val)")
  fmt.Fprintln(os.Stderr, "  void stateDel(string db, string key)")
  fmt.Fprintln(os.Stderr, "  string stateGet(string db, string key)")
  fmt.Fprintln(os.Stderr, "   stateGetByKey(string db, string key)")
  fmt.Fprintln(os.Stderr, "  void stateCreateIndex(string db, string name, string pattern, string indextype)")
  fmt.Fprintln(os.Stderr, "   stateGetByIndex(string db, string name,  params)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var parsedUrl url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Parse()
  
  if len(urlString) > 0 {
    parsedUrl, err := url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  client := state.NewStateManagerClientFactory(trans, protocolFactory)
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "disconnect":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "Disconnect requires 2 args")
      flag.Usage()
    }
    arg33 := flag.Arg(1)
    mbTrans34 := thrift.NewTMemoryBufferLen(len(arg33))
    defer mbTrans34.Close()
    _, err35 := mbTrans34.WriteString(arg33)
    if err35 != nil {
      Usage()
      return
    }
    factory36 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt37 := factory36.GetProtocol(mbTrans34)
    argvalue0 := state.NewClient()
    err38 := argvalue0.Read(jsProt37)
    if err38 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.Disconnect(value0, value1))
    fmt.Print("\n")
    break
  case "send":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "Send requires 2 args")
      flag.Usage()
    }
    arg40 := flag.Arg(1)
    mbTrans41 := thrift.NewTMemoryBufferLen(len(arg40))
    defer mbTrans41.Close()
    _, err42 := mbTrans41.WriteString(arg40)
    if err42 != nil {
      Usage()
      return
    }
    factory43 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt44 := factory43.GetProtocol(mbTrans41)
    argvalue0 := state.NewClient()
    err45 := argvalue0.Read(jsProt44)
    if err45 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.Send(value0, value1))
    fmt.Print("\n")
    break
  case "getClients":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetClients requires 1 args")
      flag.Usage()
    }
    arg47 := flag.Arg(1)
    mbTrans48 := thrift.NewTMemoryBufferLen(len(arg47))
    defer mbTrans48.Close()
    _, err49 := mbTrans48.WriteString(arg47)
    if err49 != nil {
      Usage()
      return
    }
    factory50 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt51 := factory50.GetProtocol(mbTrans48)
    argvalue0 := state.NewClient()
    err52 := argvalue0.Read(jsProt51)
    if err52 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetClients(value0))
    fmt.Print("\n")
    break
  case "setTag":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "SetTag requires 2 args")
      flag.Usage()
    }
    arg53 := flag.Arg(1)
    mbTrans54 := thrift.NewTMemoryBufferLen(len(arg53))
    defer mbTrans54.Close()
    _, err55 := mbTrans54.WriteString(arg53)
    if err55 != nil {
      Usage()
      return
    }
    factory56 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt57 := factory56.GetProtocol(mbTrans54)
    argvalue0 := state.NewClient()
    err58 := argvalue0.Read(jsProt57)
    if err58 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.SetTag(value0, value1))
    fmt.Print("\n")
    break
  case "stateCount":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "StateCount requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.StateCount(value0))
    fmt.Print("\n")
    break
  case "stateSet":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "StateSet requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    fmt.Print(client.StateSet(value0, value1, value2))
    fmt.Print("\n")
    break
  case "stateDel":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "StateDel requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.StateDel(value0, value1))
    fmt.Print("\n")
    break
  case "stateGet":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "StateGet requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.StateGet(value0, value1))
    fmt.Print("\n")
    break
  case "stateGetByKey":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "StateGetByKey requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.StateGetByKey(value0, value1))
    fmt.Print("\n")
    break
  case "stateCreateIndex":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "StateCreateIndex requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    argvalue3 := flag.Arg(4)
    value3 := argvalue3
    fmt.Print(client.StateCreateIndex(value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "stateGetByIndex":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "StateGetByIndex requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    arg76 := flag.Arg(3)
    mbTrans77 := thrift.NewTMemoryBufferLen(len(arg76))
    defer mbTrans77.Close()
    _, err78 := mbTrans77.WriteString(arg76)
    if err78 != nil { 
      Usage()
      return
    }
    factory79 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt80 := factory79.GetProtocol(mbTrans77)
    containerStruct2 := state.NewStateManagerStateGetByIndexArgs()
    err81 := containerStruct2.ReadField3(jsProt80)
    if err81 != nil {
      Usage()
      return
    }
    argvalue2 := containerStruct2.Params
    value2 := argvalue2
    fmt.Print(client.StateGetByIndex(value0, value1, value2))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
