<?php

## AUTOGENERATED OPTIONS - DO NOT EDIT
$options = array (
    'mode' => 'custom',
    'layout' => array (
        'size' => '200',
        'sizetype' => 'px',
        'type' => 'menu',
        'name' => 'col1',
        'file' => 'application.modules.dev.menus.GenCtrl',
        'title' => 'Controller List',
        'icon' => 'fa-slack',
        'inlineJS' => 'GenCtrl.js',
    ),
);
## END OF AUTOGENERATED OPTIONS

return ControllerGenerator::listCtrlForMenuTree();
