<?php 

## AUTOGENERATED OPTIONS - DO NOT EDIT
$options = array (
    'mode' => 'custom',
    'layout' => array (
        'size' => '200',
        'sizetype' => 'px',
        'type' => 'menu',
        'name' => 'col1',
        'file' => 'application.modules.dev.menus.GenEmail',
        'inlineJS' => 'GenEmail.js',
    ),
);
## END OF AUTOGENERATED OPTIONS

return EmailGenerator::listMenuTree();