<?php 

## AUTOGENERATED OPTIONS - DO NOT EDIT
$options = array (
    'mode' => 'custom',
    'layout' => array (
        'size' => '200',
        'sizetype' => 'px',
        'type' => 'menu',
        'name' => 'col1',
        'file' => 'application.modules.dev.menus.GenModel',
        'title' => 'Model',
        'icon' => 'fa-cube',
        'inlineJS' => 'GenModel.js',
    ),
);
## END OF AUTOGENERATED OPTIONS


return ModelGenerator::listMenuTree();