<?php

## AUTOGENERATED OPTIONS - DO NOT EDIT
$options = array(
    'mode'   => 'custom',
    'layout' => array(
        'size'     => '200',
        'sizetype' => 'px',
        'type'     => 'menu',
        'name'     => 'col1',
        'file'     => 'application.modules.dev.menus.GenModule',
        'title'    => 'test',
        'icon'     => 'fa-empire',
    ),
);
## END OF AUTOGENERATED OPTIONS


return ModuleGenerator::listModuleForMenuTree();
