<?php 

## AUTOGENERATED OPTIONS - DO NOT EDIT
$options = array (
    'mode' => 'custom',
);
## END OF AUTOGENERATED OPTIONS

return array (
    array (
        'label' => 'Risk Register',
        'icon' => '',
        'url' => '#',
        'items' => array (
            array (
                'label' => 'Entry',
                'icon' => '',
                'url' => '#',
            ),
            array (
                'label' => 'Display',
                'icon' => '',
                'url' => '#',
            ),
        ),
        'state' => 'collapsed',
    ),
    array (
        'label' => 'LED (Loss Event Database)',
        'icon' => '',
        'url' => '#',
        'items' => array (
            array (
                'label' => 'Entry',
                'icon' => '',
                'url' => '#',
            ),
            array (
                'label' => 'Display',
                'icon' => '',
                'url' => '#',
            ),
        ),
        'state' => 'collapsed',
    ),
    array (
        'label' => 'RKIA (Rancangan Kerja Internal Audit)',
        'icon' => '',
        'url' => '#',
        'items' => array (
            array (
                'label' => 'Entry',
                'icon' => '',
                'url' => '#',
            ),
            array (
                'label' => 'Display',
                'icon' => '',
                'url' => '#',
            ),
        ),
        'state' => 'collapsed',
    ),
    array (
        'label' => 'Surat Tugas',
        'icon' => '',
        'url' => '#',
        'items' => array (
            array (
                'label' => 'Entry',
                'icon' => '',
                'url' => '#',
            ),
            array (
                'label' => 'Display',
                'icon' => '',
                'url' => '#',
            ),
        ),
        'state' => 'collapsed',
    ),
    array (
        'label' => 'SPT Karyawan',
        'icon' => '',
        'url' => '#',
    ),
    array (
        'label' => 'Kuisioner',
        'icon' => '',
        'url' => '#',
    ),
);