<?php 

## AUTOGENERATED OPTIONS - DO NOT EDIT
$options = array (
    'mode' => 'custom',
    'layout' => array (
        'size' => '200',
        'sizetype' => 'px',
        'type' => 'menu',
        'name' => 'col1',
        'file' => 'application.modules.dev.menus.MainMenu',
        'title' => '',
        'icon' => '',
        'inlineJS' => '',
    ),
);
## END OF AUTOGENERATED OPTIONS

return array (
    array (
        'label' => 'Builder',
        'items' => array (
            array (
                'label' => 'Code Builder',
                'icon' => 'fa-code',
                'url' => '/builder',
                'formattedUrl' => '/dokman/index.php?r=builder',
            ),
            array (
                'label' => '---',
                'icon' => '',
                'url' => '#',
            ),
            array (
                'label' => 'Form Builder',
                'icon' => 'fa-file',
                'url' => '/dev/forms/index',
                'formattedUrl' => '/dokman/index.php?r=dev/forms/index',
                'state' => 'collapsed',
            ),
            array (
                'label' => '---',
                'icon' => '',
                'url' => '#',
            ),
            array (
                'label' => 'MenuTree Editor',
                'icon' => 'fa-sitemap',
                'url' => '/dev/genMenu/index',
                'formattedUrl' => '/dokman/index.php?r=dev/genMenu/index',
            ),
            array (
                'label' => '---',
                'icon' => '',
                'url' => '#',
            ),
            array (
                'label' => 'Module Builder',
                'icon' => 'fa-empire',
                'url' => '/dev/genModule/index',
                'formattedUrl' => '/dokman/index.php?r=dev/genModule/index',
            ),
            array (
                'label' => 'Model Builder',
                'icon' => 'fa-cube',
                'url' => '/dev/genModel/index',
                'formattedUrl' => '/dokman/index.php?r=dev/genModel/index',
            ),
            array (
                'label' => 'Controller Builder',
                'icon' => 'fa-slack',
                'url' => '/dev/genCtrl/index',
                'formattedUrl' => '/dokman/index.php?r=dev/genCtrl/index',
            ),
            array (
                'label' => '---',
                'icon' => '',
                'url' => '#',
            ),
            array (
                'label' => 'Email Builder',
                'icon' => 'fa-envelope',
                'url' => '/dev/genEmail/index',
                'formattedUrl' => '/dokman/index.php?r=dev/genEmail/index',
            ),
            array (
                'label' => '---',
                'icon' => '',
                'url' => '#',
            ),
            array (
                'label' => 'Service Manager',
                'icon' => 'fa-asterisk',
                'url' => '/dev/service/index',
                'formattedUrl' => '/dokman/index.php?r=dev/service/index',
            ),
        ),
        'state' => 'collapsed',
        'icon' => 'fa-gavel',
    ),
    array (
        'label' => 'Users',
        'icon' => 'fa-user',
        'url' => '',
        'items' => array (
            array (
                'label' => 'User List',
                'icon' => 'fa-user',
                'url' => '/dev/user/index',
                'formattedUrl' => '/dokman/index.php?r=dev/user/index',
            ),
            array (
                'label' => 'Role Manager',
                'icon' => 'fa-graduation-cap',
                'url' => '/dev/user/roles',
                'formattedUrl' => '/dokman/index.php?r=dev/user/roles',
            ),
        ),
        'state' => 'collapsed',
        'formattedUrl' => '/dokman/index.php',
    ),
    array (
        'label' => 'Settings',
        'icon' => 'fa-sliders',
        'url' => '/dev/setting',
        'formattedUrl' => '/dokman/index.php?r=dev/setting',
        'items' => array (
            array (
                'label' => 'Application Setting',
                'icon' => 'fa-home',
                'url' => '/dev/setting/app',
                'formattedUrl' => '/dokman/index.php?r=dev/setting/app',
                'state' => 'collapsed',
            ),
            array (
                'label' => 'Theme Setting',
                'icon' => 'fa-picture-o',
                'url' => '/dev/setting/theme',
                'formattedUrl' => '/dokman/index.php?r=dev/setting/theme',
                'state' => 'collapsed',
            ),
            array (
                'label' => 'Database Setting',
                'icon' => 'fa-database',
                'url' => '/dev/setting/database',
                'formattedUrl' => '/dokman/index.php?r=dev/setting/database',
            ),
            array (
                'label' => 'Email Setting',
                'icon' => 'fa-envelope',
                'url' => '/dev/setting/email',
                'formattedUrl' => '/dokman/index.php?r=dev/setting/email',
                'state' => 'collapsed',
            ),
            array (
                'label' => 'LDAP Setting',
                'icon' => 'fa-users',
                'url' => '/dev/setting/ldap',
                'formattedUrl' => '/dokman/index.php?r=dev/setting/ldap',
            ),
        ),
        'state' => 'collapsed',
    ),
    array (
        'label' => 'Repository',
        'icon' => 'fa-folder-open',
        'url' => '/repo/index',
        'formattedUrl' => '/dokman/index.php?r=repo/index',
    )
);