<?php 

## AUTOGENERATED OPTIONS - DO NOT EDIT
$options = array (
    'mode' => 'normal',
    'layout' => array (
        'size' => '200',
        'sizetype' => 'px',
        'type' => 'menu',
        'name' => 'col1',
        'file' => 'application.modules.dev.menus.MainMenu',
        'title' => '',
        'icon' => '',
        'inlineJS' => '',
    ),
);
## END OF AUTOGENERATED OPTIONS

return array (
    array (
        'label' => 'Builder',
        'items' => array (
            array (
                'label' => 'Form Builder',
                'icon' => 'fa-file',
                'url' => '/dev/forms/index',
                'formattedUrl' => '/eris/index.php?r=dev/forms/index',
            ),
            array (
                'label' => '---',
                'icon' => '',
                'url' => '#',
            ),
            array (
                'label' => 'MenuTree Editor',
                'icon' => 'fa-sitemap',
                'url' => '/dev/genMenu/index',
                'formattedUrl' => '/eris/index.php?r=dev/genMenu/index',
            ),
            array (
                'label' => '---',
                'icon' => '',
                'url' => '#',
            ),
            array (
                'label' => 'Module Builder',
                'icon' => 'fa-empire',
                'url' => '/dev/genModule/index',
                'formattedUrl' => '/eris/index.php?r=dev/genModule/index',
            ),
            array (
                'label' => 'Model Builder',
                'icon' => 'fa-cube',
                'url' => '/dev/genModel/index',
                'formattedUrl' => '/eris/index.php?r=dev/genModel/index',
            ),
            array (
                'label' => 'Controller Builder',
                'icon' => 'fa-slack',
                'url' => '/dev/genCtrl/index',
                'formattedUrl' => '/eris/index.php?r=dev/genCtrl/index',
            ),
            array (
                'label' => '---',
                'icon' => '',
                'url' => '#',
            ),
            array (
                'label' => 'Email Builder',
                'icon' => 'fa-envelope',
                'url' => '/dev/email/index',
                'formattedUrl' => '/eris/index.php?r=dev/email/index',
            ),
            array (
                'label' => '---',
                'icon' => '',
                'url' => '#',
            ),
            array (
                'label' => 'Service Manager',
                'icon' => 'fa-asterisk',
                'url' => '/dev/service/index',
                'formattedUrl' => '/eris/index.php?r=dev/service/index',
            ),
        ),
        'state' => 'collapsed',
        'icon' => 'fa-gavel',
    ),
    array (
        'label' => 'Users',
        'icon' => 'fa-user',
        'url' => '#',
        'items' => array (
            array (
                'label' => 'User List',
                'icon' => 'fa-user',
                'url' => '/dev/user/index',
                'formattedUrl' => '/eris/index.php?r=dev/user/index',
            ),
            array (
                'label' => 'Role Manager',
                'icon' => 'fa-graduation-cap',
                'url' => '/dev/user/roles',
                'formattedUrl' => '/eris/index.php?r=dev/user/roles',
            ),
        ),
        'state' => 'collapsed',
    ),
    array (
        'label' => 'Settings',
        'icon' => 'fa-sliders',
        'url' => '/dev/setting/app',
        'formattedUrl' => '/eris/index.php?r=dev/setting/app',
    ),
    array (
        'label' => 'Repository',
        'icon' => 'fa-folder-open',
        'url' => '/repo/index',
        'formattedUrl' => '/eris/index.php?r=repo/index',
    ),
);