<?php 

## AUTOGENERATED OPTIONS - DO NOT EDIT
$options = array (
    'mode' => 'normal',
    'layout' => array (
        'size' => '200',
        'sizetype' => 'px',
        'type' => 'menu',
        'name' => 'col1',
        'file' => 'application.modules.dev.menus.Setting',
        'icon' => 'fa-sliders',
        'title' => 'Settings',
        'menuOptions' => array (),
    ),
);
## END OF AUTOGENERATED OPTIONS

return array (
    array (
        'label' => 'Tes Menu',
        'icon' => '',
        'url' => '#',
        'items' => array (
            array (
                'label' => 'App Setting',
                'icon' => 'fa-home',
                'url' => '/dev/setting/app',
                'formattedUrl' => '/smuhrd/index.php?r=dev/setting/app',
            ),
        ),
        'state' => 'collapsed',
    ),
);