<?php 

## AUTOGENERATED OPTIONS - DO NOT EDIT
$options = array (
    'mode' => 'normal',
    'layout' => array (
        'size' => '200',
        'sizetype' => 'px',
        'type' => 'menu',
        'name' => 'col1',
        'file' => 'application.modules.dev.menus.Setting',
        'icon' => 'fa-sliders',
        'title' => 'Main Setting',
        'menuOptions' => array (),
    ),
);
## END OF AUTOGENERATED OPTIONS

return array (
    array (
        'label' => 'Application Setting',
        'icon' => 'fa-home',
        'url' => '/dev/setting/app',
        'formattedUrl' => '/smuhrd/index.php?r=dev/setting/app',
    ),
    array (
        'label' => 'Database Setting',
        'icon' => 'fa-database',
        'url' => '/dev/setting/database',
        'formattedUrl' => '/smuhrd/index.php?r=dev/setting/database',
    ),
    array (
        'label' => 'Process Manager',
        'icon' => 'fa-briefcase',
        'url' => 'dev/processManager/index',
        'formattedUrl' => '/smuhrd/index.php?r=dev/command/index',
    ),
);