// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "git.apache.org/thrift.git/lib/go/thrift"
        "svc"
)


func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  void add(Service svc)")
  fmt.Fprintln(os.Stderr, "  void remove(string name)")
  fmt.Fprintln(os.Stderr, "  string start(string name, string params)")
  fmt.Fprintln(os.Stderr, "  void stop(string name)")
  fmt.Fprintln(os.Stderr, "  void stopInstance(string pid)")
  fmt.Fprintln(os.Stderr, "  Instance getInstance(string pid)")
  fmt.Fprintln(os.Stderr, "  Service getService(string name)")
  fmt.Fprintln(os.Stderr, "  void setView(string name, string key, string value)")
  fmt.Fprintln(os.Stderr, "   getAllServices()")
  fmt.Fprintln(os.Stderr, "  string cwd()")
  fmt.Fprintln(os.Stderr, "  void quit()")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var parsedUrl url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Parse()
  
  if len(urlString) > 0 {
    parsedUrl, err := url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  client := svc.NewServiceManagerClientFactory(trans, protocolFactory)
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "add":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "Add requires 1 args")
      flag.Usage()
    }
    arg31 := flag.Arg(1)
    mbTrans32 := thrift.NewTMemoryBufferLen(len(arg31))
    defer mbTrans32.Close()
    _, err33 := mbTrans32.WriteString(arg31)
    if err33 != nil {
      Usage()
      return
    }
    factory34 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt35 := factory34.GetProtocol(mbTrans32)
    argvalue0 := svc.NewService()
    err36 := argvalue0.Read(jsProt35)
    if err36 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.Add(value0))
    fmt.Print("\n")
    break
  case "remove":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "Remove requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.Remove(value0))
    fmt.Print("\n")
    break
  case "start":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "Start requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.Start(value0, value1))
    fmt.Print("\n")
    break
  case "stop":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "Stop requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.Stop(value0))
    fmt.Print("\n")
    break
  case "stopInstance":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "StopInstance requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.StopInstance(value0))
    fmt.Print("\n")
    break
  case "getInstance":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetInstance requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetInstance(value0))
    fmt.Print("\n")
    break
  case "getService":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetService requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetService(value0))
    fmt.Print("\n")
    break
  case "setView":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "SetView requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    fmt.Print(client.SetView(value0, value1, value2))
    fmt.Print("\n")
    break
  case "getAllServices":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetAllServices requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetAllServices())
    fmt.Print("\n")
    break
  case "cwd":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "Cwd requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.Cwd())
    fmt.Print("\n")
    break
  case "quit":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "Quit requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.Quit())
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
